// Generated from src/data/languages.ts — keep in sync.
// Internal ids stay Baidu-style codes so no caller changes; the LLM is given the
// full English language name, which it handles far more reliably than a code.
export const LANGUAGE_NAMES: Record<string, string> = {
  zh: "Chinese (Simplified)",
  cht: "Chinese (Traditional)",
  yue: "Cantonese",
  wyw: "Classical Chinese",
  en: "English",
  jp: "Japanese",
  kor: "Korean",
  fra: "French",
  frn: "French (Canada)",
  frm: "Middle French",
  spa: "Spanish",
  th: "Thai",
  ara: "Arabic",
  arq: "Arabic (Algerian)",
  tua: "Arabic (Tunisian)",
  ru: "Russian",
  pt: "Portuguese",
  pot: "Portuguese (Brazil)",
  de: "German",
  log: "Low German",
  it: "Italian",
  el: "Greek",
  gra: "Ancient Greek",
  nl: "Dutch",
  pl: "Polish",
  bul: "Bulgarian",
  est: "Estonian",
  dan: "Danish",
  fin: "Finnish",
  cs: "Czech",
  rom: "Romanian",
  slo: "Slovenian",
  sk: "Slovak",
  swe: "Swedish",
  hu: "Hungarian",
  vie: "Vietnamese",
  tr: "Turkish",
  ukr: "Ukrainian",
  bel: "Belarusian",
  hrv: "Croatian",
  srp: "Serbian",
  src: "Serbian (Cyrillic)",
  bos: "Bosnian",
  mot: "Montenegrin",
  mac: "Macedonian",
  alb: "Albanian",
  lav: "Latvian",
  lit: "Lithuanian",
  lag: "Latgalian",
  ice: "Icelandic",
  fao: "Faroese",
  nor: "Norwegian",
  nob: "Norwegian Bokmål",
  nno: "Norwegian Nynorsk",
  gle: "Irish",
  gla: "Scottish Gaelic",
  wel: "Welsh",
  cor: "Cornish",
  bre: "Breton",
  glv: "Manx",
  cat: "Catalan",
  baq: "Basque",
  glg: "Galician",
  ast: "Asturian",
  arg: "Aragonese",
  oci: "Occitan",
  wln: "Walloon",
  srd: "Sardinian",
  cos: "Corsican",
  nea: "Neapolitan",
  fri: "Friulian",
  roh: "Romansh",
  lim: "Limburgish",
  fry: "Western Frisian",
  ltz: "Luxembourgish",
  lat: "Latin",
  eno: "Old English",
  sil: "Silesian",
  kah: "Kashubian",
  ups: "Upper Sorbian",
  los: "Lower Sorbian",
  ruy: "Rusyn",
  ro: "Romani",
  chv: "Chuvash",
  bak: "Bashkir",
  tat: "Tatar",
  cri: "Crimean Tatar",
  aze: "Azerbaijani",
  kir: "Kyrgyz",
  tuk: "Turkmen",
  hi: "Hindi",
  urd: "Urdu",
  ben: "Bengali",
  pan: "Punjabi",
  guj: "Gujarati",
  mar: "Marathi",
  nep: "Nepali",
  sin: "Sinhala",
  tam: "Tamil",
  tel: "Telugu",
  kan: "Kannada",
  mal: "Malayalam",
  ori: "Odia",
  asm: "Assamese",
  snd: "Sindhi",
  kas: "Kashmiri",
  san: "Sanskrit",
  mai: "Maithili",
  bho: "Bhojpuri",
  kok: "Konkani",
  div: "Dhivehi",
  per: "Persian",
  pus: "Pashto",
  kur: "Kurdish",
  bal: "Balochi",
  ir: "Iranian",
  oss: "Ossetian",
  tgk: "Tajik",
  arm: "Armenian",
  geo: "Georgian",
  heb: "Hebrew",
  yid: "Yiddish",
  syr: "Syriac",
  amh: "Amharic",
  tir: "Tigrinya",
  bli: "Blin",
  orm: "Oromo",
  som: "Somali",
  swa: "Swahili",
  afr: "Afrikaans",
  xho: "Xhosa",
  zul: "Zulu",
  sot: "Southern Sotho",
  ped: "Northern Sotho",
  nbl: "Southern Ndebele",
  tso: "Tsonga",
  ven: "Venda",
  sna: "Shona",
  nya: "Chichewa",
  bem: "Bemba",
  lug: "Luganda",
  kin: "Kinyarwanda",
  lin: "Lingala",
  kon: "Kikongo",
  ful: "Fula",
  hau: "Hausa",
  ibo: "Igbo",
  yor: "Yoruba",
  twi: "Twi",
  aka: "Akan",
  wol: "Wolof",
  kau: "Kanuri",
  kab: "Kabyle",
  ber: "Berber",
  sol: "Songhay",
  nqo: "N'Ko",
  mg: "Malagasy",
  mau: "Mauritian Creole",
  ht: "Haitian Creole",
  pap: "Papiamento",
  may: "Malay",
  id: "Indonesian",
  jav: "Javanese",
  sun: "Sundanese",
  ach: "Acehnese",
  fil: "Filipino",
  tgl: "Tagalog",
  ceb: "Cebuano",
  hil: "Hiligaynon",
  pam: "Kapampangan",
  bur: "Burmese",
  hkm: "Khmer",
  lao: "Lao",
  sha: "Shan",
  hak: "Hakha Chin",
  hmn: "Hmong",
  tet: "Tetum",
  bis: "Bislama",
  mah: "Marshallese",
  sm: "Samoan",
  mao: "Maori",
  haw: "Hawaiian",
  grn: "Guarani",
  aym: "Aymara",
  que: "Quechua",
  chr: "Cherokee",
  cre: "Cree",
  oji: "Ojibwe",
  hup: "Hupa",
  iku: "Inuktitut",
  kal: "Greenlandic",
  sme: "Northern Sami",
  ing: "Ingush",
  zaz: "Zazaki",
  epo: "Esperanto",
  ido: "Ido",
  ina: "Interlingua",
  loj: "Lojban",
  kli: "Klingon",
  mlt: "Maltese",
};

export const isKnownLanguage = (code: string) => code === "auto" || code in LANGUAGE_NAMES;

/** Chinese targets that should carry Hanyu Pinyin in the response. */
export const CHINESE_CODES = new Set(["zh", "cht", "yue", "wyw"]);
